name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
permissions:
  contents: read
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:  
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
          
      - name: Build frontend
        run: pnpm run build
      
      - name: Debug GH_TOKEN
        run: |
          echo "GH_TOKEN length: ${#GH_TOKEN}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


      - name: Build Electron app
        run: pnpm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
