name: Auto Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'package.json'
      - 'apps/*/package.json'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet HEAD~1 HEAD -- apps/ package.json apps/*/package.json; then
            echo "No changes to release"
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, will release"
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto Release
        if: steps.changes.outputs.should_release == 'true'
        run: |
          echo "🚀 Starting auto-release process..."
          node scripts/auto-release.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Electron app
        if: steps.changes.outputs.should_release == 'true'
        run: |
          echo "Building studio app..."
          cd apps/studio && yarn build
      
      - name: Publish Electron release
        if: steps.changes.outputs.should_release == 'true'
        run: |
          echo "Publishing Electron release..."
          cd apps/desktop && yarn tsc && yarn prebuild && ELECTRON_BUILDER_CACHE=/tmp/electron-builder-cache npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

